-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 10:04:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db_inventario` ;

-- -----------------------------------------------------
-- Table `db_inventario`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `stock` INT NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT '1',
  `disponibilidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_productos_categorias_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `db_inventario`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`clin_pro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`clin_pro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `no_documento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NOT NULL,
  `tipo_soporte` VARCHAR(45) NOT NULL,
  `no_soporte` VARCHAR(45) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `iva` DOUBLE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_inventario_persona_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_inventario_persona`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `db_inventario`.`clin_pro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`detalle_ingreso` (
  `id_detalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `idingreso` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `costo` DOUBLE NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`id_detalle_ingreso`),
 	INDEX `fk_mov_inventario_idx` (`idingreso`),
  INDEX `fk_mov_productos_idx` (`idproducto`),
  CONSTRAINT `fk_mov_inventario`
    FOREIGN KEY (`idingreso`)
    REFERENCES `ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mov_productos`
    FOREIGN KEY (`idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`sucursal` (
  `idsucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `no_soporte` VARCHAR(45) NOT NULL,
  `tipo_soporte` VARCHAR(45) NOT NULL,
  `iva` DOUBLE NOT NULL,
  `total_venta` FLOAT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `idsucursal` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cliente_idx` (`idcliente`),
  INDEX `fk_pedido_sucursal_idx` (`idsucursal`),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `clin_pro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_sucursal`
    FOREIGN KEY (`idsucursal`)
    REFERENCES `sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`detalle_pedido` (
  `id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
  `idpedido` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  INDEX `fk_mov_solicitud_idx` (`idpedido` ASC),
  INDEX `fk_mov_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_mov_solicitud`
    FOREIGN KEY (`idpedido`)
    REFERENCES `db_inventario`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mov_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `db_inventario`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inventario`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `no_documento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
